# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
    - "hhvm"
    - "7.0"
    - "5.6"
    - "5.5"
    - "5.4"
    - "5.3"
#    - "5.2"

# WordPress version used in first build configuration.
env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.2 WP_MULTISITE=0
    - WP_VERSION=4.1 WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.2 WP_MULTISITE=1
    - WP_VERSION=4.1 WP_MULTISITE=1

# Clones WordPress and configures our testing environment.
before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - export PLUGIN_SLUG=$(basename $(pwd))
    - cd ..
    - mv $PLUGIN_SLUG "/tmp/wordpress/wp-content/plugins/$PLUGIN_SLUG"
    - cd "/tmp/wordpress/wp-content/plugins/$PLUGIN_SLUG"

script:
    - phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
